#!/bin/bash

if [ "$#" -eq 0 -o "$1" = "-h" ]; then
  echo -e "\nUsage:\n$0 [Docker Container ID]\n"
  exit
fi

PID=$(docker inspect --format '' $1 | grep Pid | sed -e 's/"//g;s/://g;s/,//g;s/ //g;s/Pid//g')
nsenter --target $PID --mount --uts --ipc --net --pid
